### ISSUE TITLE
Feature: Allocated time

### ISSUE THREAD

**Issue by Edwardm2002** [SDS-Program-Pool/pooler#65]
Due to all feedback needing to be returned before you can get a feedback review there becomes a problem if someone in the class isn't giving feedback. Therefore a deadline/reallocation would make sense so that no one gets stuck with only 2 marks/feedback and so cant get to the mark review stage.

**Comment by ctaylor-c172** [comment]
Ideas:
1) E-Mail once per day after e.g 3 days after first allocation
AND
2) Re-Allocate code if user has not marked after e.g 7 days

Thoughts?

**Comment by Edwardm2002** [comment]
That would make sense

**Comment by Edwardm2002** [comment]
After 7 days send reminder email?

**Comment by Edwardm2002** [comment]
@ctaylor-c172 Is this going to be implemented?

**Comment by ctaylor-c172** [comment]
- Soft deadline will be implemented to 7 days.
- Students will be able to escalate and or get a re-allocation of markers.

Current ETA is within the next 48 hours.

**Comment by ctaylor-c172** [comment]
@Edwardm2002 
Escalation is in place, this will allow students to escalate if projects are not being marked.
Soft deadline of 7 days is in place for core project marking. This is based off the project upload date, not the marker allocation time and is a known flaw. But this caters to most situations so will be used for now.

This issue will be closed for now. It may be re-opened for a better implementation including jobs after e.g 10 days to auto re allocate rather than relying on student rejection or creator to press a button
